name = "sinthanai-org"
main = "./worker/index.ts"
compatibility_date = "2026-04-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"
not_found_handling = "none"

[images]
binding = "IMAGES"

[[kv_namespaces]]
binding = "VINEXT_CACHE"
id = "c4e25059c88c444cb654219fb84c2e53"

[env.production]
name = "sinthanai-org-prod"

[env.production.assets]
directory = "dist/client"
binding = "ASSETS"
not_found_handling = "none"

[env.production.images]
binding = "IMAGES"
